# Use an official Node.js runtime as a parent image
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Copy application code
COPY . .

# Install app dependencies
RUN npm install

# Build the project
RUN npm run build --workspace=@ide/backend

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run the app
CMD ["npm", "run", "start", "--workspace=@ide/backend"]
